import json
import requests
import re
import os
import pandas as pd
from pandas import DataFrame
from math import radians, sin, cos, sqrt, atan2
from openai import OpenAI

# star imports are not really good
from src.plotter import *

# global client
# client = openai.OpenAI(api_key=os.getenv('OPENAI_API_KEY'))


# def generate_gpt_apartment_report(air_quality_data: dict) -> str:
#     """
#     Generate a realestate_report for an apartment based on the air quality data

#     Args:
#         air_quality_data (dict): dictionary with air quality data

#     Returns:
#         str: realestate_report generated by GPT-3.5-turbo
#     """

#     # prompt should be moved to a separate file
#     response = client.chat.completions.create(
#         model="gpt-3.5-turbo",
#         messages=[
#             {
#                 "role": "system",
#                 "content": "Hey! Based on the values of PM2.5, PM10 and CO in the air provide a realestate_report overview of the area of the real estate I am thinking of buying. Also add recommendations on living in the area with polluted air. Write each sentence"
#                            "on a new line, and each sentence should be shorter than 7 words, add new lines if the sentence is longer. Don't put periods at the ends of the sentences. "
#                            "Provide the answer in the following format and respond in russian language: "
#                            "Recommendations are:"
#                            "1."
#                            "2."
#                            "3."
#                            "..."
#             },
#             {
#                 "role": "user",
#                 "content": f"PM2.5 value {air_quality_data['pm25']}, PM10 value {air_quality_data['pm10']},"
#                            f"CO value: {air_quality_data['co']}"

#             }
#         ],
#         max_tokens=150
#     )
#     report = response.choices[0].message.content

#     return report


# def read_local_apartment_page(filepath: str) -> dict:
#     """
#     Read the HTML file with the apartment data

#     Args:
#         filepath (str): path to the HTML file

#     Returns:
#         dict: dictionary with the apartment data"""

#     apartment_info = {
#         "location": None,
#         "street": None,
#         "floor number": None,
#         "area": None,
#         "room_type": None,
#         "year of construction": None,
#     }
#     try:
#         with open(filepath, 'r', encoding='utf-8') as f:
#             html_content = f.read()
#             print("HTML code read successfully.")
#     except Exception as e:
#         print(f"An error occurred: {e}")

#     phys_data = get_phys_data(html_content)
#     apartment_info["location"] = get_coordinates(html_content)
#     apartment_info["floor number"] = phys_data["floor number"]
#     apartment_info["street"] = phys_data["street"]
#     apartment_info["area"] = phys_data["area"]
#     apartment_info["room_type"] = phys_data["room_type"]
#     apartment_info["year of construction"] = phys_data["year of construction"]

#     return apartment_info


# def download_apartment_webpage(url: str) -> dict:
#     """
#     Download the HTML file with the apartment data

#     Args:
#         url (str): URL to the apartment data

#     Returns:
#         dict: dictionary with the apartment data"""
#     realestate_dict = {
#         "location": None,
#         "street": None,
#         "floor number": None,
#         "area": None,
#         "room_type": None,
#         "year of construction": None,
#     }

#     html_content = ""

#     try:
#         response = requests.get(url)
#         if response.status_code == 200:
#             html_content = response.text
#         else:
#             print(f"Failed to download HTML. Status code: {response.status_code}")
#             return None
#     except Exception as e:
#         print(f"An error occurred: {e}")
#         return None

#     phys_data = get_phys_data(html_content)
#     realestate_dict["location"] = get_coordinates(html_content)
#     realestate_dict["floor number"] = phys_data["floor number"]
#     realestate_dict["street"] = phys_data["street"]
#     realestate_dict["area"] = phys_data["area"]
#     realestate_dict["room_type"] = phys_data["room_type"]
#     realestate_dict["year of construction"] = phys_data["year of construction"]

#     return realestate_dict


## this function is to be removed, we are not
## going to scrape the html page
# def get_phys_data(apartment_html_data: str) -> dict:
    """
    Get the physical data of the apartment

    Args:
        apartment_html_data (str): HTML content of the apartment data

    Returns:
        dict: dictionary with the physical data of the apartment
    """
    # 
    room_data_pattern = r'(\d+-комнатная квартира), (\d+ м²), (\d+/\d+ этаж), ([^,]+) за'
    construction_date_pattern = r'<div class="offer__info-item" data-name="house.year">.*?<div class="offer__advert-short-info">(\d+)</div>'
    phys_data_dict = {
        "street": None,
        "floor number": None,
        "year of construction": None,
        "area": None,
        "room_type": None
    }

    match = re.search(
        construction_date_pattern, apartment_html_data, re.DOTALL)
    if match:
        year = match.group(1)
        phys_data_dict["year of construction"] = year
    else:
        print("Year data not found.")
    match = re.search(room_data_pattern, apartment_html_data)
    if match:
        room_type = match.group(1)
        area = match.group(2)
        floor = match.group(3)
        street = match.group(4)
        phys_data_dict["street"] = street
        phys_data_dict["floor number"] = floor
        phys_data_dict["area"] = area
        phys_data_dict["room_type"] = room_type
    else:
        print("Data not found.")

    return phys_data_dict

## this function is to be removed, we are not
# def get_coordinates(apartment_data: str) -> str:
    """
    Get the coordinates of the apartment

    Args:
        apartment_data (str): HTML content of the apartment data

    Returns:
        str: coordinates of the apartment
    """
    # it's to remove tags, make the text lowercase, etc etc, preprocess it
    pattern = r'"lat":(-?\d+\.\d+),"lon":(-?\d+\.\d+)'
    match = re.search(pattern, apartment_data)
    if match:
        lat = float(match.group(1))
        lon = float(match.group(2))
        lat_lon_combined = f"{lat},{lon}"
        return lat_lon_combined

    return "Coordinates were not found."


# def get_sensor_location_id_from_manual_input(location: str) -> int:
#     """
#     Get the location ID of the closest sensor to the provided location

#     Args:
#         location (str): latitude and longitude of the provided location

#     Returns:
#         int: location ID of the closest sensor"""
#     sensor_dataframe = read_sergek_data()
#     sensor_locations_df = pd.DataFrame(sensor_dataframe)
#     sensor_locations_df = sensor_locations_df.drop(
#         sensor_locations_df.index[0])

#     provided_location = location
#     latitude, longitude = map(float, provided_location.split(','))

#     provided_location_dict = {
#         "Latitude": latitude,
#         "Longitude": longitude
#     }
#     closest_sensor = find_closest_sensor(
#         sensor_locations_df, provided_location_dict)
#     closest_sensor_dict = closest_sensor.to_dict()

#     return closest_sensor_dict["location_id"]


# def get_sensor_location_id(url: str) -> int:
#     """
#     Get the location ID of the closest sensor to the provided location

#     Args:
#         url (str): URL to the apartment data

#     Returns:
#         int: location ID of the closest sensor"""
#     sensor_dataframe = read_sergek_data()
#     phys_data = download_apartment_webpage(url)

#     sensor_locations_df = pd.DataFrame(sensor_dataframe)
#     sensor_locations_df = sensor_locations_df.drop(
#         sensor_locations_df.index[0])
#     provided_location = phys_data["location"]
#     latitude, longitude = map(float, provided_location.split(','))
#     provided_location_dict = {
#         "Latitude": latitude,
#         "Longitude": longitude
#     }
#     closest_sensor = find_closest_sensor(
#         sensor_locations_df, provided_location_dict)
#     closest_sensor_dict = closest_sensor.to_dict()

#     return closest_sensor_dict["location_id"]

# ## this function is to be removed
# # def create_apartment_report_from_manual_input(apartment_location: str) -> str:
#     """
#     Create a realestate_report for an apartment based on the air quality data and the coordinates

#     Args:
#         apartment_location (str): lat and long of the apartment location

#     Returns:
#         str: path to the generated realestate_report"""

#     sensor_dataframe = read_sergek_data()
#     sensor_locations_df = pd.DataFrame(sensor_dataframe)
#     sensor_locations_df = sensor_locations_df.drop(
#         sensor_locations_df.index[0])
#     provided_location = apartment_location
#     latitude, longitude = map(float, provided_location.split(','))
#     provided_location_dict = {
#         "Latitude": latitude,
#         "Longitude": longitude
#     }
#     closest_sensor = find_closest_sensor(
#         sensor_locations_df, provided_location_dict)
#     closest_sensor_dict = closest_sensor.to_dict()

#     data_processed = calculate_air_quality_index(closest_sensor_dict)
#     aq_metrics_for_gpt_report = {
#         "pm25": closest_sensor_dict['pm25'],
#         "pm10": closest_sensor_dict['pm10'],
#         "co": closest_sensor_dict['co']
#     }
#     print(closest_sensor_dict)
#     data_processed.update({'latitude': closest_sensor_dict['Latitude']})
#     data_processed.update({'longitude': closest_sensor_dict['Longitude']})
#     data_processed.update({'pm25': int(float(closest_sensor_dict['pm25']))})
#     data_processed.update({'pm10': int(float(closest_sensor_dict['pm10']))})
#     data_processed.update({'co': int(float(closest_sensor_dict['co']))})
#     data_processed.update(
#         {"realestate_report": generate_gpt_apartment_report(
#             aq_metrics_for_gpt_report)}
#     )

#     path_to_report = generate_report_for_an_apartment(
#         data_processed['latitude'],
#         data_processed['longitude'],
#         int(data_processed["aq_index_numeric"]),
#         data_processed["aq_index_color"],
#         data_processed["color_pm25"],
#         data_processed["color_pm10"],
#         data_processed["color_co"],
#         data_processed["pm25"],
#         data_processed["pm10"],
#         data_processed["co"],
#         data_processed["realestate_report"])

#     return path_to_report

## this function is to be removed
# def create_apartment_report_from_link(url: str) -> str:
#     """
#         Create a realestate_report for an apartment based on the air quality data and the html code
#         of the apartment listing

#         Args:
#             apartment_location (str): lat and long of the apartment location

#         Returns:
#             str: path to the generated realestate_report"""
#     sensor_dataframe = read_sergek_data()
#     phys_data = download_apartment_webpage(url)

#     sensor_locations_df = pd.DataFrame(sensor_dataframe)
#     sensor_locations_df = sensor_locations_df.drop(
#         sensor_locations_df.index[0])
#     provided_location = phys_data["location"]
#     latitude, longitude = map(float, provided_location.split(','))
#     provided_location_dict = {
#         "Latitude": latitude,
#         "Longitude": longitude
#     }
#     closest_sensor = find_closest_sensor(
#         sensor_locations_df, provided_location_dict)
#     closest_sensor_dict = closest_sensor.to_dict()

#     data_processed = calculate_air_quality_index(closest_sensor_dict)
#     aq_metrics_for_gpt_report = {
#         "pm25": closest_sensor_dict['pm25'],
#         "pm10": closest_sensor_dict['pm10'],
#         "co": closest_sensor_dict['co']
#     }
#     data_processed.update({'latitude': closest_sensor_dict['Latitude']})
#     data_processed.update({'longitude': closest_sensor_dict['Longitude']})
#     data_processed.update({'pm25': int(float(closest_sensor_dict['pm25']))})
#     data_processed.update({'pm10': int(float(closest_sensor_dict['pm10']))})
#     data_processed.update({'co': int(float(closest_sensor_dict['co']))})
#     data_processed.update(
#         {"realestate_report": generate_gpt_apartment_report(
#             aq_metrics_for_gpt_report)}
#     )
#     path_to_report = generate_report_for_an_apartment(
#         data_processed['latitude'],
#         data_processed['longitude'],
#         int(data_processed["aq_index_numeric"]),
#         data_processed["aq_index_color"],
#         data_processed["color_pm25"],
#         data_processed["color_pm10"],
#         data_processed["color_co"],
#         data_processed["pm25"],
#         data_processed["pm10"],
#         data_processed["co"],
#         data_processed["realestate_report"]
#     )

#     return path_to_report


## this function is to be removed
# def test_local_file_generation() -> str:
#     """
#         Create a realestate_report for an apartment based on the air quality data and the local html code of
#         apartment listing


#         Returns:
#     str: path to the generated realestate_report
#     """
#     sensor_dataframe = read_sergek_data()
#     phys_data = read_local_apartment_page(
#         "../assets/html_testing_files/apartment.txt")
#     sensor_locations_df = pd.DataFrame(sensor_dataframe)
#     sensor_locations_df = sensor_locations_df.drop(
#         sensor_locations_df.index[0])
#     provided_location = phys_data["location"]
#     latitude, longitude = map(float, provided_location.split(','))
#     provided_location_dict = {
#         "Latitude": latitude,
#         "Longitude": longitude
#     }

#     closest_sensor = find_closest_sensor(
#         sensor_locations_df, provided_location_dict)
#     closest_sensor_dict = closest_sensor.to_dict()
#     data_processed = calculate_air_quality_index(closest_sensor_dict)

#     aq_metrics_for_gpt_report = {
#         "pm25": int(float(closest_sensor_dict['pm25'])),
#         "pm10": int(float(closest_sensor_dict['pm10'])),
#         "co": int(float(closest_sensor_dict['co']))
#     }
#     data_processed.update({'pm25': int(float(closest_sensor_dict['pm25']))})
#     data_processed.update({'pm10': int(float(closest_sensor_dict['pm10']))})
#     data_processed.update({'co': int(float(closest_sensor_dict['co']))})
#     data_processed.update(
#         {"realestate_report": generate_gpt_apartment_report(
#             aq_metrics_for_gpt_report)}
#     )
#     path_to_report = generate_report_for_an_apartment(
#         int(data_processed["aq_index_numeric"]),
#         data_processed["aq_index_color"],
#         data_processed["color_pm25"],
#         data_processed["color_pm10"],
#         data_processed["color_co"],
#         data_processed["pm25"],
#         data_processed["pm10"],
#         data_processed["co"],
#         data_processed["realestate_report"]
#     )

#     return path_to_report